# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VersioningCli < Formula
  desc "Versioning Utilities CLI"
  homepage "https://github.com/iac-factory/versioning-cli"
  version "0.1.4"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.4/versioning-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "519cd80438bd7a510ad940efaaefe59d28d829a40c396f0339c4a28002a7de05"

      def install
        bin.install "versioning-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.4/versioning-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "c29d54d66fe57ad6d404d5e44978a3b035cc9461b01851ca305a492929c4d88f"

      def install
        bin.install "versioning-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.4/versioning-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2935c1089d9626f70a9fad74994dd0e133883a6107ecc107b7eda56a81a2c2bb"

      def install
        bin.install "versioning-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.4/versioning-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "f65ddeb2759180beda10f2aa315ca88b022fe75d3e14ebc83a8e8e4570da62d0"

      def install
        bin.install "versioning-cli"
      end
    end
  end

  conflicts_with "versioning-cli"
end
