# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCobraCli < Formula
  desc "Example CLI Template"
  homepage "https://github.com/iac-factory/go-cobra-cli"
  version "0.0.9"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "go" => :build
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.9/go-cobra-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5061b2ea1bb86591f6a6689f9aea47e3614398cdcb4aa12ec2c653f2d71bd631"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.9/go-cobra-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "afcd250c3c98d0acda7c1a87ff73d6fb13ca54017e5121af87a9915a62f01dc6"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.9/go-cobra-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "de19b586cfb6470617f2e1a8f5c354f041d06c8e53bd824a321c26e734a9dbb2"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.9/go-cobra-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "a96a0c24364f6f8d885e5148aac2b1cd7a23a958712d0df1bdb96e1648ced45c"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  conflicts_with "go-cobra-cli"

  def caveats
    <<~EOS
      Internal Usage Only
    EOS
  end
end
