# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCobraCli < Formula
  desc "Example CLI Template"
  homepage "https://github.com/iac-factory/go-cobra-cli"
  version "0.1.2"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.1.2/go-cobra-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7fd9169aae335624b24ef44213d5268eb180c1f85388e10dd4c289c2193a9f95"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.1.2/go-cobra-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "89090d171b4b8080974e2616c23bf70d506bda653d739710c2c70f4849919886"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.1.2/go-cobra-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8d7ea8541ab9ca967828e1d6d6e022b6934dd7c3fa156a016ee69aad055baa63"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.1.2/go-cobra-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "e305e36e62185eb9b4d2621d21544b8c08473286ed03c44e5ed13cf96ae0773d"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  conflicts_with "go-cobra-cli"

  def caveats
    <<~EOS
      Internal Usage Only
    EOS
  end
end
