# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCobraCli < Formula
  desc "Example CLI Template"
  homepage "https://github.com/iac-factory/go-cobra-cli"
  version "0.0.10"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.10/go-cobra-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d73a6ff887998dc827e36e4f43eaec64f428bd12ab3e2ec173cb986ce8abfb6b"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.10/go-cobra-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0d2a65ce5a7d1d2a3125eced7686a48b5515f3898eb361d75a627cf36071542"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.10/go-cobra-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c2b76771e919758b45bcc22fb5db63501acbe871832d3d4b698af2eb050b7c5d"

      def install
        bin.install "go-cobra-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iac-factory/go-cobra-cli/releases/download/v0.0.10/go-cobra-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "28636b6844c6116b58540c4d44a7f6c03b8819c34cd3d2ee02e85daa44e235db"

      def install
        bin.install "go-cobra-cli"
      end
    end
  end

  conflicts_with "go-cobra-cli"

  def caveats
    <<~EOS
      Internal Usage Only
    EOS
  end
end
