# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VersioningCli < Formula
  desc "Versioning Utilities CLI"
  homepage "https://github.com/iac-factory/versioning-cli"
  version "0.1.9"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.9/versioning-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "2d6c353d38ef7839a216667a045cda784ae1ba872a492563c92ca6b0f332b43a"

      def install
        bin.install "versioning-cli"
      end
    end
    on_arm do
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.9/versioning-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "275636d19d3287e514aa99125a5e7b2ff9d84ab5f44d38b1f5d7efe694aeef26"

      def install
        bin.install "versioning-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.9/versioning-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
        sha256 "1b42ec561a4d00732c884415ce7b4fa667e3f26918e5155385b18eb150b1f168"

        def install
          bin.install "versioning-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.9/versioning-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "c0471dd491122c5e468a5ed1518c137ffeb8f9ecc66c39ce45952bbcfc208174"

        def install
          bin.install "versioning-cli"
        end
      end
    end
  end

  conflicts_with "versioning-cli"
end
