# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VersioningCli < Formula
  desc "Versioning Utilities CLI"
  homepage "https://github.com/iac-factory/versioning-cli"
  version "0.1.10"
  license "MIT"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.10/versioning-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "0ceb20946ea48a4401c0375420566cd0faf1f3b9cacdaab66551c09eab368bb5"

      def install
        bin.install "versioning-cli"
      end
    end
    on_arm do
      url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.10/versioning-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "556f72bfe6f58305132ee90cc5d68629f02472a057e212998765910c9e29177d"

      def install
        bin.install "versioning-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.10/versioning-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
        sha256 "a3b92509211843d7d4d41c581f79a9702b60d9ff70ecc27ce6fa37cccfd1c2fd"

        def install
          bin.install "versioning-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/iac-factory/versioning-cli/releases/download/v0.1.10/versioning-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "6c356104ec8153365521a062ab707a9dde0524c7debd12d589351685e78c8751"

        def install
          bin.install "versioning-cli"
        end
      end
    end
  end

  conflicts_with "versioning-cli"
end
